Header header

# command names
int32 MODE_LOAD_GAINS                     = 4
int32 MODE_NECK_UP                        = 9
int32 MODE_NECK_DOWN                      = 10
int32 MODE_NECK_SET                       = 11
int32 MODE_ERIC_TELEOP                    = 17
int32 MODE_SFENG_TELEOP                   = 33
int32 MODE_SFENG_JOINTS                   = 15

int32 KEYBOARD_0                          = 48
int32 KEYBOARD_1                          = 49
int32 KEYBOARD_2                          = 50
int32 KEYBOARD_3                          = 51
int32 KEYBOARD_4                          = 52
int32 KEYBOARD_5                          = 53
int32 KEYBOARD_6                          = 54
int32 KEYBOARD_7                          = 55
int32 KEYBOARD_8                          = 56
int32 KEYBOARD_9                          = 57

int32 KEYBOARD_A  			                  = 97
int32 KEYBOARD_B  			                  = 98
int32 KEYBOARD_C  			                  = 99
int32 KEYBOARD_D  			                  = 100
int32 KEYBOARD_E  			                  = 101
int32 KEYBOARD_F  			                  = 102
int32 KEYBOARD_G  			                  = 103
int32 KEYBOARD_H  			                  = 104
int32 KEYBOARD_I  			                  = 105
int32 KEYBOARD_J  			                  = 106
int32 KEYBOARD_K  			                  = 107
int32 KEYBOARD_L  			                  = 108
int32 KEYBOARD_M  			                  = 109
int32 KEYBOARD_N  			                  = 110
int32 KEYBOARD_O  			                  = 111
int32 KEYBOARD_P  			                  = 112
int32 KEYBOARD_Q  			                  = 113
int32 KEYBOARD_R  			                  = 114
int32 KEYBOARD_S  			                  = 115
int32 KEYBOARD_T  			                  = 116
int32 KEYBOARD_U  			                  = 117
int32 KEYBOARD_V  			                  = 118
int32 KEYBOARD_W  			                  = 119
int32 KEYBOARD_X  			                  = 120
int32 KEYBOARD_Y  			                  = 121
int32 KEYBOARD_Z                  	      = 122

int32 KEYBOARD_CA  			                  = 65
int32 KEYBOARD_CB  			                  = 66
int32 KEYBOARD_CC  			                  = 67
int32 KEYBOARD_CD  			                  = 68
int32 KEYBOARD_CE  			                  = 69
int32 KEYBOARD_CF  			                  = 70
int32 KEYBOARD_CG  			                  = 71
int32 KEYBOARD_CH  			                  = 72
int32 KEYBOARD_CI  			                  = 73
int32 KEYBOARD_CJ  			                  = 74
int32 KEYBOARD_CK  			                  = 75
int32 KEYBOARD_CL  			                  = 76
int32 KEYBOARD_CM  			                  = 77
int32 KEYBOARD_CN  			                  = 78
int32 KEYBOARD_CO  			                  = 79
int32 KEYBOARD_CP  			                  = 80
int32 KEYBOARD_CQ  			                  = 81
int32 KEYBOARD_CR  			                  = 82
int32 KEYBOARD_CS  			                  = 83
int32 KEYBOARD_CT  			                  = 84
int32 KEYBOARD_CU  			                  = 85
int32 KEYBOARD_CV  			                  = 86
int32 KEYBOARD_CW  			                  = 87
int32 KEYBOARD_CX  			                  = 88
int32 KEYBOARD_CY  			                  = 89
int32 KEYBOARD_CZ                  	      = 90


int32 KEYBOARD_SPACE                      = 32

int32 KEYBOARD_LESS					              = 44
int32 KEYBOARD_MORE					              = 46
int32 KEYBOARD_UP_ARROW				            = 961
int32 KEYBOARD_DOWN_ARROW                 = 962
int32 KEYBOARD_LEFT_ARROW                 = 963
int32 KEYBOARD_RIGHT_ARROW                = 964

int32[] cmd
# Generalized command / parameter message
float64[] param
